import type { TemplateType } from './wedding'

export type LayoutStyle = 'centered' | 'left' | 'elegant' | 'modern'
export type DecorationStyle = 'arch' | 'floral' | 'geometric' | 'line' | 'double-line' | 'hearts' | 'stars' | 'waves' | 'dots' | 'none'
export type EventCardStyle = 'bordered' | 'accent-left' | 'filled' | 'minimal'
export type PhotoStyle = 'fullscreen' | 'rounded' | 'circle' | 'top-banner'

export interface TemplateStyle {
  id: TemplateType
  name: string
  description: string
  layout: LayoutStyle
  decoration: DecorationStyle
  eventCard: EventCardStyle
  photo: PhotoStyle
  showCountdown: boolean
  showDressCode: boolean
  showArch: boolean
  coupleSeparator: '&' | '❤' | '+' | '×' | '♡' | '∞' | '•' | '~'
}

export const templateStyles: TemplateStyle[] = [
  {
    id: 'classic',
    name: 'Classic Chic',
    description: 'Élégance intemporelle, tons sobres et typographie serif',
    layout: 'centered',
    decoration: 'arch',
    eventCard: 'bordered',
    photo: 'fullscreen',
    showCountdown: true,
    showDressCode: true,
    showArch: true,
    coupleSeparator: '&',
  },
  {
    id: 'boho',
    name: 'Champêtre / Boho',
    description: 'Ambiance nature, tons terreux et détails floraux',
    layout: 'centered',
    decoration: 'floral',
    eventCard: 'accent-left',
    photo: 'fullscreen',
    showCountdown: true,
    showDressCode: true,
    showArch: false,
    coupleSeparator: '&',
  },
  {
    id: 'minimalist',
    name: 'Minimaliste Moderne',
    description: 'Design épuré, monochrome, ligne claire',
    layout: 'left',
    decoration: 'line',
    eventCard: 'minimal',
    photo: 'top-banner',
    showCountdown: false,
    showDressCode: true,
    showArch: false,
    coupleSeparator: '&',
  },
  {
    id: 'elegant',
    name: 'Élégant Doré',
    description: 'Raffinement avec accents dorés et lignes doubles',
    layout: 'elegant',
    decoration: 'double-line',
    eventCard: 'bordered',
    photo: 'fullscreen',
    showCountdown: true,
    showDressCode: true,
    showArch: true,
    coupleSeparator: '∞',
  },
  {
    id: 'romantic',
    name: 'Romantique',
    description: 'Cœurs délicats, tons doux et ambiance amoureuse',
    layout: 'centered',
    decoration: 'hearts',
    eventCard: 'accent-left',
    photo: 'fullscreen',
    showCountdown: true,
    showDressCode: true,
    showArch: false,
    coupleSeparator: '❤',
  },
  {
    id: 'modern',
    name: 'Moderne Tranché',
    description: 'Lignes géométriques, design contemporain audacieux',
    layout: 'modern',
    decoration: 'geometric',
    eventCard: 'filled',
    photo: 'top-banner',
    showCountdown: false,
    showDressCode: true,
    showArch: false,
    coupleSeparator: '+',
  },
  {
    id: 'rustic',
    name: 'Rustique',
    description: 'Ambiance campagne, bois et matières naturelles',
    layout: 'left',
    decoration: 'dots',
    eventCard: 'filled',
    photo: 'fullscreen',
    showCountdown: true,
    showDressCode: true,
    showArch: false,
    coupleSeparator: '&',
  },
  {
    id: 'luxury',
    name: 'Luxe / Prestige',
    description: 'Design sophistiqué, finitions précieuses',
    layout: 'elegant',
    decoration: 'double-line',
    eventCard: 'bordered',
    photo: 'fullscreen',
    showCountdown: true,
    showDressCode: true,
    showArch: true,
    coupleSeparator: '∞',
  },
  {
    id: 'vintage',
    name: 'Vintage Rétro',
    description: 'Charme d\'antan, couleurs sépia et détails anciens',
    layout: 'centered',
    decoration: 'floral',
    eventCard: 'bordered',
    photo: 'fullscreen',
    showCountdown: true,
    showDressCode: true,
    showArch: true,
    coupleSeparator: '&',
  },
  {
    id: 'tropical',
    name: 'Tropical',
    description: 'Ambiance exotique, couleurs vives et motifs végétaux',
    layout: 'centered',
    decoration: 'waves',
    eventCard: 'accent-left',
    photo: 'fullscreen',
    showCountdown: true,
    showDressCode: true,
    showArch: false,
    coupleSeparator: '❤',
  },
  {
    id: 'geometric',
    name: 'Géométrique',
    description: 'Motifs géométriques, angles droits et symétrie',
    layout: 'modern',
    decoration: 'geometric',
    eventCard: 'filled',
    photo: 'rounded',
    showCountdown: false,
    showDressCode: true,
    showArch: false,
    coupleSeparator: '+',
  },
  {
    id: 'playful',
    name: 'Ludique / Moderne',
    description: 'Esprit décontracté, couleurs pop et pastel',
    layout: 'left',
    decoration: 'stars',
    eventCard: 'minimal',
    photo: 'rounded',
    showCountdown: false,
    showDressCode: true,
    showArch: false,
    coupleSeparator: '•',
  },
  {
    id: 'classic-modern',
    name: 'Classico-Moderne',
    description: 'Fusion classique/contemporain, équilibré et sobre',
    layout: 'left',
    decoration: 'line',
    eventCard: 'bordered',
    photo: 'top-banner',
    showCountdown: true,
    showDressCode: true,
    showArch: false,
    coupleSeparator: '&',
  },
  {
    id: 'soft',
    name: 'Douceur / Pastel',
    description: 'Teintes pastel, légèreté et délicatesse',
    layout: 'centered',
    decoration: 'dots',
    eventCard: 'minimal',
    photo: 'rounded',
    showCountdown: true,
    showDressCode: true,
    showArch: false,
    coupleSeparator: '♡',
  },
  {
    id: 'bold',
    name: 'Audacieux',
    description: 'Typographie forte, contrastes marqués, style affirmé',
    layout: 'modern',
    decoration: 'none',
    eventCard: 'filled',
    photo: 'fullscreen',
    showCountdown: false,
    showDressCode: true,
    showArch: false,
    coupleSeparator: '×',
  },
]
